### ISSUE TITLE
[BUG] SCHEMATIC error

### ISSUE THREAD

**Issue by ms-emp** [Badisi/auth-js#32]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Library version

latest

### Description

I'm getting an error `registry.flatten is not a function` when using `ng add @badisi/ngx-auth `

### Environment

- **OS Name**: Windows
- **System Model Name**:
- **npm**:
- **Node.js**:

**Comment by Badisi** [comment]
Can you please provide the result of the following command : `ng version` ?

**Comment by ms-emp** [comment]
16.1.5

**Comment by Badisi** [comment]
There are breaking changes with `Angular 16+`.

You can use the latest alpha release which should solve your problem:
```sh
ng add @badisi/ngx-auth@3.0.0-alpha.1
```
This version is also fully **Ivy** compliant (not more **ViewEngine**), which should improve your application build process.

**Comment by ms-emp** [comment]
Thanks so much. It's an awesome library.

**Comment by ms-emp** [comment]
Where can I fork version 3.0.0-alpha.1?

**Comment by Badisi** [comment]
:tada: Released in [@badisi/ngx-auth@3.0.0](https://github.com/Badisi/auth-js/releases/tag/@badisi/ngx-auth@3.0.0) :package::rocket:

**Comment by Badisi** [comment]
Pay attention that **standalone** application is not yet supported, so the `schematic` will currently works only on legacy app.
