### ISSUE TITLE
[DOCS] Wrong default for mobileWindowPresentationStyle

### ISSUE THREAD

**Issue by ms-emp** [Badisi/auth-js#33]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Library version

latest

### Description

The comment for `mobileWindowPresentationStyle` says that the default is `fullscreen`, but it's actually `popover`.

See: [here](https://github.com/Badisi/auth-js/blob/66712331c68adec14d553b125576e23c1acbe99c/projects/auth-js/oidc/oidc-auth-manager.ts#L35)

**Comment by Badisi** [comment]
:tada: Released in [@badisi/auth-js@1.0.0](https://github.com/Badisi/auth-js/releases/tag/@badisi/auth-js@1.0.0) :package::rocket:

**Comment by Badisi** [comment]
:tada: Released in [@badisi/ngx-auth@3.0.0](https://github.com/Badisi/auth-js/releases/tag/@badisi/ngx-auth@3.0.0) :package::rocket:
