### ISSUE TITLE
[BUG] Query params are duplicated after redirect

### ISSUE THREAD

**Issue by ms-emp** [Badisi/auth-js#35]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Library version

3.0.0-alpha.1

### Description

When the user navigates to a protected page and includes some query parameters, the query parameters are duplicated when he comes back to the app after logging in.

### Steps to reproduce

See [this](https://github.com/ms-emp/auth-test) test app, clone, run, log in using credentials from [here](https://badisi.github.io/auth-js/site/documentation/playground), click on Logout, then click on Page 2 with params and see the output on the page.

### Environment

- **Angular version**: 16

**Comment by ms-emp** [comment]
So I found the bug.

In AuthService line 167 `absUrl` already contains the query string so we shouldn't append `value.search`.

![image](https://github.com/Badisi/auth-js/assets/93929177/9d749db0-e8c4-47d5-b7eb-7ef98c893354)

**Comment by Badisi** [comment]
Thanks for the investigation !
I'll try to find some time in the upcoming days to have a look into it.

**Comment by ms-emp** [comment]
Hi,

I created a fix branch, but I'm getting a 403 when I try to push the branch to GitHub?!

**Comment by Badisi** [comment]
I've been really busy these past few months and I haven't had any time to dedicate to this library, unfortunately..
I'll do my best to get everything sorted out this week.
Thanks for the PR, and sorry for the inconvenience.

**Comment by Badisi** [comment]
Issue must have been introduced after Angular 14 (because I can reproduce it with Angular 16 but not Angular 14).

`URL.href` is returning the whole url anyway, so there is definitely no need to add search params.

Fix will be available in the next release.

**Comment by Badisi** [comment]
Also, the Angular demo app now has a query params settings to play with:
https://badisi.github.io/auth-js/demo-app/ngx-auth

**Comment by Badisi** [comment]
:tada: Released in [@badisi/ngx-auth@3.0.0](https://github.com/Badisi/auth-js/releases/tag/@badisi/ngx-auth@3.0.0) :package::rocket:
